# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Upload the first SARIF file
      - name: Upload SARIF file 1
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-reports\database-5a7786812dd4-2024-01-11.sarif

      # # Upload the second SARIF file
      # - name: Upload SARIF file 2
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: sarif-reports\database-a632c89dd778-2024-06-07.sarif

      # # Upload the third SARIF file
      # - name: Upload SARIF file 3
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: sarif-reports\database-b8b8ebcf851d-2017-04-11.sarif